sonar.projectKey=${env.SONAR_PROJECT_KEY}
sonar.organization=${env.SONAR_ORGANIZATION}
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,bun.lockb
