sonar.projectKey=ddd-example-ts
sonar.projectName=ddd-example-ts
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,bun.lockb
